name: clean_architecture
description: "A Flutter project with a clean architecture implementation."

publish_to: 'GitHub'

version: 0.0.1+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  bloc: ^8.1.4
  cached_network_image: ^3.4.1
  chopper: ^8.0.3
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.2.1
  flutter_inappwebview: ^6.1.5
  get: ^4.6.6
  isar: ^3.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.14
  chopper_generator: ^8.0.3
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/environments/
    - assets/images/

